import type { Metadata } from "next";
import localFont from "next/font/local";
import { Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import PageTransitionWrapper from "@/components/PageTransitionWrapper";
import SmoothScroll from "@/components/SmoothScroll";
import Footer from "@/components/Footer";

const satoshi = localFont({
  variable: "--font-sans",
  display: "swap",
  src: [
    { path: "../../public/fonts/Satoshi-Light.otf", weight: "300", style: "normal" },
    { path: "../../public/fonts/Satoshi-LightItalic.otf", weight: "300", style: "italic" },
    { path: "../../public/fonts/Satoshi-Regular.otf", weight: "400", style: "normal" },
    { path: "../../public/fonts/Satoshi-Italic.otf", weight: "400", style: "italic" },
    { path: "../../public/fonts/Satoshi-Medium.otf", weight: "500", style: "normal" },
    { path: "../../public/fonts/Satoshi-MediumItalic.otf", weight: "500", style: "italic" },
    { path: "../../public/fonts/Satoshi-Bold.otf", weight: "700", style: "normal" },
    { path: "../../public/fonts/Satoshi-BoldItalic.otf", weight: "700", style: "italic" },
    { path: "../../public/fonts/Satoshi-Black.otf", weight: "900", style: "normal" },
    { path: "../../public/fonts/Satoshi-BlackItalic.otf", weight: "900", style: "italic" },
    { path: "../../public/fonts/ClashDisplay-Bold.otf", weight: "700", style: "normal" },
  ],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Tayseer Alrahhal - Web Developer",
  description: "Generated by create next app",
  icons: {
    icon: "",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${satoshi.variable} ${geistMono.variable} antialiased`}>
        <main className="relative">
          <div className="fixed top-0 left-0 right-0 w-full h-[60px] bg-linear-to-b from-(--backdrop) to-transparent"></div>
          <Header />
          <SmoothScroll>
            <PageTransitionWrapper>
              {children}
            </PageTransitionWrapper>
          </SmoothScroll>
          <Footer />
          <div className="max-md:hidden fixed bottom-0 left-0 right-0 w-full h-[60px] bg-linear-to-t from-(--backdrop) to-transparent"></div>
        </main>
      </body>
    </html>
  );
}
